### ISSUE TITLE
可以放出来应用截图来看看吗

### ISSUE THREAD

**Issue by zion223** [brokes6/MusicPlayerDome#1]

**Comment by brokes6** [comment]
已添加

**Comment by zion223** [comment]
这个“云村”界面 是安卓网易云音乐官方应用里面的云村->广场 这个界面吗

**Comment by brokes6** [comment]
不是，因为那个api中并没有云村广场的数据接口，所以我这里是使用的云村热评墙里的文章和歌曲

**Comment by brokes6** [comment]
来伪装成是云村广场

**Comment by zion223** [comment]
http://62.234.57.125:3000/ 这是我在腾讯云部署的一个NeteaseCloudMusicApi的服务 如果你不介意的话 可以直接用这个。我也在写这个的Android应用你可以去我的主页看看。

**Comment by brokes6** [comment]
好的好的，感谢了
